apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: check-sum
  namespace: default
spec:
  workloadRuntime: wasmedge
  image: rep_for_open/checksum:0.1.0
  imageCredentials:
    name: push-secret
  build:
    build:
    builder: openfunction/buildah:v1.23.1
    shipwright:
      strategy:
        kind: ClusterBuildStrategy
        name: buildah
    srcRepo:
      url: "https://github.com/ziyuecheng/grad_tests.git"
      sourceSubPath: "checksum"
      revision: "main"
  serving:
    scaleOptions:
      minReplicas: 0
    template:
      containers:
        - command:
            - /check_sum.wasm
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 30
            tcpSocket:
              port: 8080
          name: function
    triggers:
      http:
        port: 8080
        route:
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /echo